esphome:
  name: esphome-zehnder-fan
  friendly_name: ESPHome Zehnder fan
  project:
    name: srslynow.${friendly_name}
    version: v1

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

# SPI configuration for CC1101
spi:
  id: spi_bus
  clk_pin: GPIO6   # SCK
  mosi_pin: GPIO7  # MOSI
  miso_pin: GPIO2  # MISO

# External components
external_components:
  - source:
      type: git
      url: https://github.com/srslynow/esphome-zehnder
      ref: main
    refresh: 60sec
    components: [zehnder_fan]

# Fan configuration with CC1101
fan:
  - platform: zehnder_fan
    id: ventilation_fan
    name: Mechanical Ventilation
    spi_id: spi_bus

    # CC1101 Pin Configuration
    cs_pin: GPIO10      # CS/SS
    gdo0_pin: GPIO3     # GDO0 (data ready interrupt)
    gdo2_pin: GPIO4     # GDO2 (optional)

button:
  - platform: restart
    name: Restart Controller
    disabled_by_default: true

  - platform: template
    name: Pair with Fan
    icon: mdi:wifi
    entity_category: config
    on_press:
      - lambda: |-
          id(ventilation_fan).start_pairing();
